package com.ebikes.organizations.enums;

public enum DocumentType {
  BUSINESS_REGISTRATION_CERT,
  CERTIFICATE_OF_COMPLIANCE,
  CERTIFICATE_OF_INCORPORATION,
  COUNTY_PERMIT,
  HEALTH_CERTIFICATE,
  KRA_PIN_CERT,
  MEMORANDUM_ARTICLES,
  NATIONAL_ID,
  PARTNERSHIP_DEED
}
