--comment: create organizations table to manage business entities with onboarding and compliance tracking
CREATE TABLE organizations.organizations (
     id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
     activated_at        TIMESTAMPTZ,
     addresses           JSONB        NOT NULL DEFAULT '[]',
     approved_at         TIMESTAMPTZ,
     compliance_status   VARCHAR(50)  NOT NULL DEFAULT 'COMPLIANT',
     created_at          TIMESTAMPTZ  NOT NULL,
     created_by          VARCHAR(36)  NOT NULL,
     deactivated_at      TIMESTAMPTZ,
     display_name        VARCHAR(255) NOT NULL,
     email               VARCHAR(255) NOT NULL,
     incorporation_date  DATE,
     kra_pin             VARCHAR(11),
     legal_name          VARCHAR(255) NOT NULL,
     owner_id            VARCHAR(36)  NOT NULL,
     phone_number        VARCHAR(20)  NOT NULL,
     registration_number VARCHAR(100),
     registration_type   VARCHAR(50)  NOT NULL,
     rejection_reason    TEXT,
     status              VARCHAR(50)  NOT NULL DEFAULT 'PENDING_APPROVAL',
     updated_at          TIMESTAMPTZ,
     updated_by          VARCHAR(36),
     version             INTEGER       NOT NULL DEFAULT 1,

     CONSTRAINT pk_organizations
         PRIMARY KEY (id)
);

--comment: add check constraints for organizations table
ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_activation_requires_active
        CHECK (activated_at IS NULL OR status = 'ACTIVE');

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_addresses_is_array
        CHECK (jsonb_typeof(addresses) = 'array');

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_addresses_size
        CHECK (char_length(addresses::text) <= 32768);

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_approved_at_requires_approved_or_active
        CHECK (approved_at IS NULL OR status IN ('APPROVED', 'ACTIVE', 'DEACTIVATED'));

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_compliance_status
        CHECK (compliance_status IN ('COMPLIANT', 'NON_COMPLIANT', 'SUSPENDED'));

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_deactivation_requires_deactivated
        CHECK (deactivated_at IS NULL OR status = 'DEACTIVATED');

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_email_format
        CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_kra_pin_format
        CHECK (kra_pin IS NULL OR kra_pin ~ '^[A-Z][0-9]{9}[A-Z]$');

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_phone_format
        CHECK (phone_number ~ '^\+?[0-9]{10,15}$');

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_registration_type
        CHECK (registration_type IN ('FOREIGN_ENTITY', 'LIMITED_LIABILITY_ENTITY', 'PARTNERSHIP', 'REGISTERED_COMPANY', 'SOLE_PROPRIETOR'));

ALTER TABLE organizations.organizations
    ADD CONSTRAINT chk_organizations_status
        CHECK (status IN ('ACTIVE', 'APPROVED', 'DEACTIVATED', 'PENDING_APPROVAL', 'REJECTED'));

--comment: create indexes for the organizations table
CREATE INDEX idx_organizations_compliance_status ON organizations.organizations (compliance_status);
CREATE INDEX idx_organizations_created_by        ON organizations.organizations (created_by);
CREATE INDEX idx_organizations_email             ON organizations.organizations (email);
CREATE INDEX idx_organizations_owner_id          ON organizations.organizations (owner_id);
CREATE INDEX idx_organizations_status            ON organizations.organizations (status);
CREATE UNIQUE INDEX uq_organizations_legal_name  ON organizations.organizations (legal_name);

--comment: add table and column comments for organizations
COMMENT ON TABLE organizations.organizations IS
    'Business organizations with onboarding workflow and compliance tracking. '
        'Core identity fields are immutable after creation. Status transitions follow a strict '
        'lifecycle: PENDING_APPROVAL → APPROVED → ACTIVE, with REJECTED and DEACTIVATED as terminal states. '
        'Timestamp columns activated_at, approved_at, and deactivated_at are cross-validated against '
        'status via check constraints.';

COMMENT ON COLUMN organizations.organizations.id                  IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN organizations.organizations.activated_at        IS 'Timestamp when organization transitioned to ACTIVE - null until activation occurs';
COMMENT ON COLUMN organizations.organizations.addresses           IS 'JSONB array of address value objects with optional geocoding for business registration and billing. Must be a JSON array.';
COMMENT ON COLUMN organizations.organizations.approved_at         IS 'Timestamp when organization was approved by checker - persists through subsequent ACTIVE and DEACTIVATED transitions';
COMMENT ON COLUMN organizations.organizations.compliance_status   IS 'Current compliance state - updated when critical documents expire. Defaults to COMPLIANT on creation.';
COMMENT ON COLUMN organizations.organizations.created_at          IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN organizations.organizations.created_by          IS 'Keycloak user ID of the actor who submitted the organization - immutable';
COMMENT ON COLUMN organizations.organizations.deactivated_at      IS 'Timestamp when organization was deactivated - set only on transition to DEACTIVATED';
COMMENT ON COLUMN organizations.organizations.display_name        IS 'Organization display name for UI presentation';
COMMENT ON COLUMN organizations.organizations.email               IS 'Primary contact email address';
COMMENT ON COLUMN organizations.organizations.incorporation_date  IS 'Date of business incorporation';
COMMENT ON COLUMN organizations.organizations.kra_pin             IS 'Kenya Revenue Authority PIN - format: one uppercase letter, nine digits, one uppercase letter (e.g. A000000000Z)';
COMMENT ON COLUMN organizations.organizations.legal_name          IS 'Registered business legal name - must be unique across platform. Immutable after activation.';
COMMENT ON COLUMN organizations.organizations.owner_id            IS 'Keycloak user ID of the organization owner';
COMMENT ON COLUMN organizations.organizations.phone_number        IS 'Primary contact phone number';
COMMENT ON COLUMN organizations.organizations.registration_number IS 'Government-issued business registration number';
COMMENT ON COLUMN organizations.organizations.registration_type   IS 'Type of business entity - determines required documentation for compliance';
COMMENT ON COLUMN organizations.organizations.rejection_reason    IS 'Reason provided by checker on rejection - surfaced to submitter for resubmission guidance';
COMMENT ON COLUMN organizations.organizations.status              IS 'Current onboarding workflow state. Valid transitions: PENDING_APPROVAL → APPROVED → ACTIVE; PENDING_APPROVAL/APPROVED → REJECTED; ACTIVE → DEACTIVATED.';
COMMENT ON COLUMN organizations.organizations.updated_at          IS 'Timestamp of last state transition in UTC';
COMMENT ON COLUMN organizations.organizations.updated_by          IS 'Keycloak user ID of actor who performed the last state transition';
COMMENT ON COLUMN organizations.organizations.version             IS 'Optimistic locking version for concurrency control during maker-checker workflow';