--comment: create branches table to manage physical operating locations
CREATE TABLE organizations.branches (
    id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    branch_name         VARCHAR(255) NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    created_by          VARCHAR(36)  NOT NULL,
    deactivated_at      TIMESTAMPTZ,
    deactivation_reason TEXT,
    display_name        VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    operating_hours     JSONB        NOT NULL DEFAULT '[]',
    organization_id     UUID         NOT NULL,
    phone_number        VARCHAR(20)  NOT NULL,
    status              VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
    updated_at          TIMESTAMPTZ,
    updated_by          VARCHAR(36),

    CONSTRAINT pk_branches
        PRIMARY KEY (id),

    CONSTRAINT fk_branches_organization
        FOREIGN KEY (organization_id)
            REFERENCES organizations.organizations (id)
            ON DELETE RESTRICT
);

--comment: add check constraints for the branches table
ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_deactivation_requires_deactivated
        CHECK (deactivated_at IS NULL OR status = 'DEACTIVATED');

ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_deactivation_reason_requires_deactivated
        CHECK (deactivation_reason IS NULL OR status = 'DEACTIVATED');

ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_email_format
        CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_operating_hours_is_array
        CHECK (jsonb_typeof(operating_hours) = 'array');

ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_operating_hours_size
        CHECK (char_length(operating_hours::text) <= 8192);

ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_phone_format
        CHECK (phone_number ~ '^\+?[0-9]{10,15}$');

ALTER TABLE organizations.branches
    ADD CONSTRAINT chk_branches_status
        CHECK (status IN ('ACTIVE', 'DEACTIVATED', 'SUSPENDED'));

--comment: create indexes for branches table
CREATE INDEX idx_branches_email             ON organizations.branches (email);
CREATE INDEX idx_branches_organization      ON organizations.branches (organization_id);
CREATE INDEX idx_branches_status            ON organizations.branches (status);
CREATE UNIQUE INDEX uq_branches_org_name    ON organizations.branches (organization_id, lower(branch_name));

--comment: add table and column comments for branches
COMMENT ON TABLE organizations.branches IS
    'Physical operating locations belonging to an organization. '
        'Core identity fields are immutable after creation. Status transitions follow: '
        'ACTIVE → SUSPENDED, ACTIVE → DEACTIVATED, SUSPENDED → ACTIVE. '
        'DEACTIVATED is terminal. deactivated_at and deactivation_reason are cross-validated '
        'against status via check constraints.';

COMMENT ON COLUMN organizations.branches.id                  IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN organizations.branches.branch_name         IS 'Branch name - unique within organization, case-insensitive';
COMMENT ON COLUMN organizations.branches.created_at          IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN organizations.branches.created_by          IS 'Keycloak user ID of the actor who created the branch - immutable';
COMMENT ON COLUMN organizations.branches.deactivated_at      IS 'Timestamp when branch was deactivated - set only on transition to DEACTIVATED';
COMMENT ON COLUMN organizations.branches.deactivation_reason IS 'Reason provided at deactivation - present only when status is DEACTIVATED';
COMMENT ON COLUMN organizations.branches.display_name        IS 'Branch display name for UI presentation';
COMMENT ON COLUMN organizations.branches.email               IS 'Branch contact email address';
COMMENT ON COLUMN organizations.branches.operating_hours IS 'JSONB array of DaySchedule entries, each containing dayOfWeek, opens, and closes in HH:mm 24-hour format. Must be a JSON array. Empty array is valid and means no operating hours configured.';
COMMENT ON COLUMN organizations.branches.organization_id     IS 'Foreign key to parent organization - cannot be deleted while branches exist';
COMMENT ON COLUMN organizations.branches.phone_number        IS 'Branch contact phone number';
COMMENT ON COLUMN organizations.branches.status              IS 'Operational status. Valid transitions: ACTIVE → SUSPENDED, ACTIVE → DEACTIVATED, SUSPENDED → ACTIVE. DEACTIVATED is terminal.';
COMMENT ON COLUMN organizations.branches.updated_at          IS 'Timestamp of last state transition in UTC';
COMMENT ON COLUMN organizations.branches.updated_by          IS 'Keycloak user ID of actor who performed the last state transition';