--comment: create a branch_addresses table for routing and assignment strategy queries
CREATE TABLE organizations.branch_addresses (
    id              UUID         NOT NULL DEFAULT gen_random_uuid(),
    address_tag     VARCHAR(50)  NOT NULL,
    branch_id       UUID         NOT NULL,
    city            VARCHAR(100) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    created_by      VARCHAR(36)  NOT NULL,
    latitude        DECIMAL(10, 8),
    longitude       DECIMAL(11, 8),
    postal_code     VARCHAR(20),
    street_address  VARCHAR(500) NOT NULL,
    updated_at      TIMESTAMPTZ,
    updated_by      VARCHAR(36),

    CONSTRAINT pk_branch_addresses
        PRIMARY KEY (id),

    CONSTRAINT fk_branch_addresses_branch
        FOREIGN KEY (branch_id)
            REFERENCES organizations.branches (id)
            ON DELETE CASCADE
);

--comment: add check constraints for the branch_addresses table
ALTER TABLE organizations.branch_addresses
    ADD CONSTRAINT chk_branch_addresses_coordinates
        CHECK ((latitude IS NULL) = (longitude IS NULL));

ALTER TABLE organizations.branch_addresses
    ADD CONSTRAINT chk_branch_addresses_tag
        CHECK (address_tag IN ('PRIMARY', 'BILLING', 'SHIPPING', 'BRANCH_LOCATION'));

--comment: create indexes for the branch_addresses table
CREATE INDEX idx_branch_addresses_branch          ON organizations.branch_addresses (branch_id);
CREATE INDEX idx_branch_addresses_geocode         ON organizations.branch_addresses (latitude, longitude);
CREATE UNIQUE INDEX uq_branch_addresses_branch_tag ON organizations.branch_addresses (branch_id, address_tag);

--comment: add table and column comments for branch_addresses
COMMENT ON TABLE organizations.branch_addresses IS
    'Child entity storing branch physical addresses. Geocoding is optional at creation '
        'but required for routing and distance-based assignment queries from other bounded contexts. '
        'Latitude and longitude are cross-validated - both must be present or both must be absent.';

COMMENT ON COLUMN organizations.branch_addresses.id             IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN organizations.branch_addresses.address_tag    IS 'Address purpose classification - must be unique per branch';
COMMENT ON COLUMN organizations.branch_addresses.branch_id      IS 'Foreign key to parent branch - cascade delete when branch is removed';
COMMENT ON COLUMN organizations.branch_addresses.city           IS 'City name for address identification';
COMMENT ON COLUMN organizations.branch_addresses.country        IS 'Country name';
COMMENT ON COLUMN organizations.branch_addresses.created_at     IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN organizations.branch_addresses.created_by     IS 'Keycloak user ID of the actor who created the address - immutable';
COMMENT ON COLUMN organizations.branch_addresses.latitude       IS 'Geographic latitude coordinate - required for routing queries. Must be present if longitude is present.';
COMMENT ON COLUMN organizations.branch_addresses.longitude      IS 'Geographic longitude coordinate - required for routing queries. Must be present if latitude is present.';
COMMENT ON COLUMN organizations.branch_addresses.postal_code    IS 'Postal code for address identification';
COMMENT ON COLUMN organizations.branch_addresses.street_address IS 'Street address for physical location identification';
COMMENT ON COLUMN organizations.branch_addresses.updated_at     IS 'Timestamp of last update in UTC';
COMMENT ON COLUMN organizations.branch_addresses.updated_by     IS 'Keycloak user ID of actor who performed the last update';