--comment: create a documents table to manage compliance documentation
CREATE TABLE organizations.documents (
     id                      UUID         NOT NULL DEFAULT gen_random_uuid(),
     created_at              TIMESTAMPTZ  NOT NULL,
     created_by              VARCHAR(36)  NOT NULL,
     document_type           VARCHAR(50)  NOT NULL,
     expiry_date             DATE,
     file_name               VARCHAR(255),
     file_size_bytes         BIGINT,
     file_storage_url        VARCHAR(1000),
     mime_type               VARCHAR(100),
     organization_id         UUID,
     replaces_document_id    UUID,
     status                  VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
     updated_at              TIMESTAMPTZ,
     updated_by              VARCHAR(36),
     uploaded_at             TIMESTAMPTZ,
     version                 BIGINT       NOT NULL DEFAULT 0,

     CONSTRAINT pk_documents
         PRIMARY KEY (id),

     CONSTRAINT fk_documents_organization
         FOREIGN KEY (organization_id)
             REFERENCES organizations.organizations (id)
             ON DELETE RESTRICT,

     CONSTRAINT fk_documents_replaces
         FOREIGN KEY (replaces_document_id)
             REFERENCES organizations.documents (id)
             ON DELETE SET NULL
);

--comment: add check constraints for the documents table
ALTER TABLE organizations.documents
    ADD CONSTRAINT chk_documents_file_storage_url_required
        CHECK (status = 'PENDING' OR file_storage_url IS NOT NULL);

ALTER TABLE organizations.documents
    ADD CONSTRAINT chk_documents_status
        CHECK (status IN ('ACTIVE', 'EXPIRED', 'PENDING', 'REPLACED', 'UPLOADED'));

ALTER TABLE organizations.documents
    ADD CONSTRAINT chk_documents_type
        CHECK (document_type IN (
                                 'BUSINESS_REGISTRATION_CERT',
                                 'CERTIFICATE_OF_COMPLIANCE',
                                 'CERTIFICATE_OF_INCORPORATION',
                                 'COUNTY_PERMIT',
                                 'HEALTH_CERTIFICATE',
                                 'KRA_PIN_CERT',
                                 'MEMORANDUM_ARTICLES',
                                 'NATIONAL_ID',
                                 'PARTNERSHIP_DEED'));

--comment: create indexes for the documents table
CREATE INDEX idx_documents_expiry_date           ON organizations.documents (expiry_date);
CREATE INDEX idx_documents_organization          ON organizations.documents (organization_id);
CREATE INDEX idx_documents_org_type             ON organizations.documents (organization_id, document_type);
CREATE INDEX idx_documents_status               ON organizations.documents (status);
CREATE UNIQUE INDEX uq_documents_file_storage_url       ON organizations.documents (file_storage_url) WHERE file_storage_url IS NOT NULL;
CREATE UNIQUE INDEX uq_documents_org_type_active ON organizations.documents (organization_id, document_type) WHERE status = 'ACTIVE';

--comment: add table and column comments for documents
COMMENT ON TABLE organizations.documents IS
    'Compliance documents with lifecycle tracking. Documents begin as PENDING on upload initiation, '
        'transition to UPLOADED on client confirmation, ACTIVE on checker approval, REPLACED when a '
        'newer version supersedes them, and EXPIRED when their expiry date is reached. '
        'file_storage_url is required for all non-PENDING documents enforced via check constraint.';

COMMENT ON COLUMN organizations.documents.id                   IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN organizations.documents.created_at           IS 'Record creation timestamp in UTC - immutable';
COMMENT ON COLUMN organizations.documents.created_by           IS 'Keycloak user ID of the actor who initiated the upload - immutable';
COMMENT ON COLUMN organizations.documents.document_type        IS 'Type of compliance document - determines required documents per business registration type';
COMMENT ON COLUMN organizations.documents.expiry_date          IS 'Document expiration date - triggers compliance status updates when reached';
COMMENT ON COLUMN organizations.documents.file_name            IS 'Original filename of uploaded document';
COMMENT ON COLUMN organizations.documents.file_size_bytes      IS 'File size in bytes - populated on upload confirmation';
COMMENT ON COLUMN organizations.documents.file_storage_url     IS 'Storage key where document file is stored - required for all non-PENDING documents';
COMMENT ON COLUMN organizations.documents.mime_type            IS 'MIME type of uploaded document file';
COMMENT ON COLUMN organizations.documents.organization_id      IS 'Foreign key to parent organization - null until associated post-upload';
COMMENT ON COLUMN organizations.documents.replaces_document_id IS 'Self-referential FK to the document this record supersedes - null for original submissions';
COMMENT ON COLUMN organizations.documents.status               IS 'Document lifecycle status. Valid transitions: PENDING→UPLOADED, UPLOADED→ACTIVE, ACTIVE→REPLACED, ACTIVE→EXPIRED, EXPIRED→REPLACED, REPLACED→ACTIVE (rollback only)';
COMMENT ON COLUMN organizations.documents.updated_at           IS 'Timestamp of last state transition in UTC';
COMMENT ON COLUMN organizations.documents.updated_by           IS 'Keycloak user ID of actor who performed the last state transition';
COMMENT ON COLUMN organizations.documents.uploaded_at          IS 'Timestamp when upload was confirmed by client - null until confirmed';
COMMENT ON COLUMN organizations.documents.version              IS 'Optimistic locking version for concurrent replacement control';