--comment: create an outbox table for transactional event publication with at-least-once delivery guarantee
CREATE TABLE organizations.outbox (
      id           UUID         NOT NULL DEFAULT gen_random_uuid(),
      created_at   TIMESTAMPTZ  NOT NULL,
      event_type   VARCHAR(100) NOT NULL,
      payload      JSONB        NOT NULL,
      retry_count  INTEGER      NOT NULL DEFAULT 0,
      routing_key  VARCHAR(200),
      status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
      updated_at   TIMESTAMPTZ,

      CONSTRAINT pk_outbox
          PRIMARY KEY (id)
);

--comment: add check constraints for outbox table
ALTER TABLE organizations.outbox
    ADD CONSTRAINT chk_outbox_retry_count
        CHECK (retry_count >= 0);

ALTER TABLE organizations.outbox
    ADD CONSTRAINT chk_outbox_status
        CHECK (status IN ('FAILED', 'PENDING', 'SENT'));

--comment: create indexes for outbox table
CREATE INDEX idx_outbox_created_at ON organizations.outbox (created_at);
CREATE INDEX idx_outbox_pending     ON organizations.outbox (status) WHERE status = 'PENDING';

--comment: add table and column comments for outbox
COMMENT ON TABLE organizations.outbox IS
    'Transactional outbox for at-least-once event delivery. Written atomically alongside domain '
        'state changes within the same transaction. Polled by relay process for publication to '
        'RabbitMQ. PENDING awaits relay, SENT confirms published, FAILED after max retries.';

COMMENT ON COLUMN organizations.outbox.id          IS 'Primary key - UUID generated by application, database default is safety net';
COMMENT ON COLUMN organizations.outbox.created_at  IS 'Timestamp when event was written to outbox - immutable';
COMMENT ON COLUMN organizations.outbox.event_type  IS 'Domain event type - used to identify the event for consumers';
COMMENT ON COLUMN organizations.outbox.payload     IS 'Full event payload as JSONB - contains all data needed by consumers';
COMMENT ON COLUMN organizations.outbox.retry_count IS 'Number of publication attempts - incremented by relay on transient failures';
COMMENT ON COLUMN organizations.outbox.routing_key IS 'RabbitMQ topic exchange routing key - determines which consumers receive the event';
COMMENT ON COLUMN organizations.outbox.status      IS 'Publication state. PENDING awaits relay, SENT confirms published, FAILED after max retries exhausted';
COMMENT ON COLUMN organizations.outbox.updated_at  IS 'Timestamp of last status transition - updated by relay process, not by user request context';